/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example
import com.lib.CustomLib

class App {
    val greeting: String
        get() {
            return "Hello World!. Here is " + CustomLib.ID
        }
}

fun main() {
    println(App().greeting)
}
